apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: alex-best-express-sample-app
  app.kubernetes.io/instance: alex-best-express-sample-app-instance
  app.kubernetes.io/name: alex-best-express-sample-app
